### ISSUE TITLE
python porblems

### ISSUE THREAD

**Issue by H3wastooshort** [MS3FGX/CheapWX#1]
`Reading sensor...
Traceback (most recent call last):
  File "./wu_upload.py", line 30, in <module>
    sensor = BME280(mode=BME280_OSAMPLE_8)
  File "/home/pi/Adafruit_Python_BME280/Adafruit_BME280.py", line 131, in __init__
    self._device = i2c.get_i2c_device(address, **kwargs)
  File "build/bdist.linux-armv6l/egg/Adafruit_GPIO/I2C.py", line 66, in get_i2c_device
TypeError: __init__() got an unexpected keyword argument 'mode'
`
I think that there is a problem with py2 & py3...

**Comment by MS3FGX** [comment]
Since I created this project the upstream BME280 driver went through many changes. I just pushed a commit that should fix the sensor init, see if that clears the error up.

**Comment by H3wastooshort** [comment]
ill check...

**Comment by H3wastooshort** [comment]
fixed it!
